"""
WAF / Firewall Detection Module
Primary engine: wafw00f (industry standard)
Fallback engine: Weighted signature analysis to avoid false positives
All code is strictly in English.
"""

import json
import logging
import re
import subprocess
import tempfile
from typing import Dict, Optional, Tuple, List

import requests

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------
# Helper: Normalize URL
# ------------------------------------------------------------------
def normalize_url(url: str) -> str:
    """Ensure URL has a scheme and remove duplicate prefixes."""
    if not url.startswith(('http://', 'https://')):
        url = 'https://' + url
    # Fix double scheme if malformed
    if url.startswith('https://https://'):
        url = url.replace('https://https://', 'https://')
    elif url.startswith('http://http://'):
        url = url.replace('http://http://', 'http://')
    return url


# ------------------------------------------------------------------
# Fallback Signature Database (Weighted)
# ------------------------------------------------------------------
FALLBACK_SIGNATURES: Dict[str, Dict] = {
    "Cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-polished"],
        "cookies": ["__cfduid", "__cf_bm", "cf_clearance"],
        "body": ["cloudflare", "cf-ray"],
        "weight": 10,
    },
    "AWS WAF": {
        "headers": ["x-amzn-requestid", "x-amz-cf-id", "x-amzn-trace-id"],
        "cookies": ["aws-waf-token"],
        "body": ["aws-waf", "request blocked"],
        "weight": 8,
    },
    "Imperva / Incapsula": {
        "headers": ["x-iinfo", "x-cdn", "x-imperva"],
        "cookies": ["visid_incap", "incap_ses"],
        "body": ["incapsula", "imperva"],
        "weight": 9,
    },
    "Sucuri": {
        "headers": ["x-sucuri-id", "x-sucuri-cache"],
        "cookies": ["sucuri_cloudproxy"],
        "body": ["sucuri", "cloudproxy", "sucuri.net"],
        "weight": 8,
    },
    "F5 BIG-IP": {
        "headers": ["x-wa-info"],
        "cookies": ["bigip", "ts"],
        "body": ["f5", "big-ip", "request was blocked"],
        "weight": 7,
    },
    "Akamai": {
        "headers": ["x-akamai-transformed", "x-akamai-request-id"],
        "cookies": ["ak_bmsc", "bm_sv"],
        "body": ["akamai", "ghost"],
        "weight": 8,
    },
    "ModSecurity": {
        "headers": [],
        "cookies": [],
        "body": ["modsecurity", "mod_security", "this error was generated by mod_security"],
        "weight": 6,
    },
    "Barracuda": {
        "headers": ["x-barracuda"],
        "cookies": ["barracuda_"],
        "body": ["barracuda", "access denied"],
        "weight": 7,
    },
    "Wordfence": {
        "headers": [],
        "cookies": ["wfvt_", "wordfence"],
        "body": ["wordfence", "wf_"],
        "weight": 6,
    },
    "CloudFront": {
        "headers": ["x-amz-cf-id", "x-amz-cf-pop"],
        "cookies": [],
        "body": ["cloudfront"],
        "weight": 6,
    },
    "Fastly": {
        "headers": ["x-fastly", "x-served-by", "x-cache"],
        "cookies": [],
        "body": ["fastly"],
        "weight": 6,
    },
}


def _fallback_detect(url: str, timeout: int = 30) -> Tuple[Optional[str], str]:
    """
    Custom weighted detection used when wafw00f fails or is not installed.
    Returns (firewall_name, evidence) or (None, reason).
    """
    try:
        response = requests.get(
            url,
            timeout=timeout,
            allow_redirects=True,
            verify=False,
            headers={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}
        )

        headers_lower = {k.lower(): v for k, v in response.headers.items()}
        body_lower = response.text.lower()
        cookie_str = str(response.cookies).lower()

        scores: Dict[str, int] = {}
        match_details: Dict[str, List[str]] = {}

        for waf_name, sig in FALLBACK_SIGNATURES.items():
            score = 0
            details = []

            # Check headers (highest confidence)
            for h in sig.get("headers", []):
                if h in headers_lower:
                    score += sig["weight"]
                    details.append(f"header:{h}")

            # Check cookies
            for c in sig.get("cookies", []):
                if c in cookie_str:
                    score += sig["weight"] - 2
                    details.append(f"cookie:{c}")

            # Check body patterns (lowest confidence)
            for pattern in sig.get("body", []):
                if re.search(pattern, body_lower, re.IGNORECASE):
                    score += 3
                    details.append(f"body:{pattern}")

            if score > 0:
                scores[waf_name] = score
                match_details[waf_name] = details

        # Determine best match with threshold
        if scores:
            best = max(scores, key=scores.get)
            if scores[best] >= 5:  # Threshold to avoid false positives (e.g. axiler.com)
                evidence = f"Custom detection: {', '.join(match_details[best][:2])}"
                return best, evidence

        return None, "No WAF indicators found (fallback)"

    except requests.exceptions.Timeout:
        return None, "Connection timeout during fallback detection"
    except Exception as e:
        return None, f"Fallback error: {str(e)}"


def _wafw00f_detect(url: str, timeout: int = 60) -> Tuple[Optional[str], str]:
    """
    Primary detection using wafw00f command-line tool.
    Returns (firewall_name, evidence) or (None, error/reason).
    """
    try:
        # Quick check if wafw00f is available
        subprocess.run(
            ["wafw00f", "--help"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=5,
            check=False
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None, "wafw00f not installed or not in PATH"

    tmp_path = None
    try:
        # Create temp file for JSON output
        with tempfile.NamedTemporaryFile(mode="w+", suffix=".json", delete=False) as tmp:
            tmp_path = tmp.name

        # Run wafw00f with JSON output
        cmd = ["wafw00f", url, "-o", tmp_path, "--format", "json"]

        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False
        )

        if result.returncode != 0:
            return None, f"wafw00f exited with code {result.returncode}"

        # Parse the JSON output
        with open(tmp_path, "r") as f:
            data = json.load(f)

        if data and data.get("detected"):
            waf_name = data.get("waf", "Unknown")
            confidence = data.get("confidence", 0)
            evidence = f"wafw00f detected: {waf_name} (confidence: {confidence}%)"
            return waf_name, evidence

        return None, "wafw00f found no WAF"

    except subprocess.TimeoutExpired:
        return None, "wafw00f timeout (60s)"
    except json.JSONDecodeError:
        return None, "Failed to parse wafw00f JSON output"
    except Exception as e:
        return None, f"wafw00f error: {str(e)}"
    finally:
        # Clean up temp file
        if tmp_path:
            import os
            try:
                os.unlink(tmp_path)
            except OSError:
                pass


CDN_SERVICES = {"CloudFront", "Cloudflare", "Fastly", "Akamai", "Amazon CloudFront"}


def _is_cdn(name: Optional[str]) -> bool:
    if not name:
        return False
    return any(cdn.lower() in name.lower() for cdn in CDN_SERVICES)


def _build_firewall_result(name: Optional[str], evidence: str) -> Dict:
    """Normalize output: separate CDN presence from WAF protection."""
    cdn_detected = _is_cdn(name)
    waf_detected = bool(name) and not cdn_detected

    return {
        "detected": bool(name),
        "firewall_name": name,
        "cdn_detected": cdn_detected,
        "waf_detected": waf_detected,
        "cdn_name": name if cdn_detected else None,
        "waf_name": name if waf_detected else None,
        "evidence": evidence,
    }


# ------------------------------------------------------------------
# Main Public Function
# ------------------------------------------------------------------
def detect_firewall(url: str) -> Dict:
    """
    Detect CDN and WAF layers using wafw00f primary + fallback.

    Returns format expected by frontend renderFirewall():
    {
        "detected": bool,
        "firewall_name": str or None,
        "cdn_detected": bool,
        "waf_detected": bool,
        "cdn_name": str or None,
        "waf_name": str or None,
        "evidence": str
    }
    """
    url = normalize_url(url)

    # Step 1: Try wafw00f (primary)
    waf_name, evidence = _wafw00f_detect(url, timeout=60)
    if waf_name:
        return _build_firewall_result(waf_name, evidence)

    # Step 2: Fallback to custom weighted detection
    logger.info(f"wafw00f did not detect WAF for {url}, using fallback...")
    waf_name, evidence = _fallback_detect(url, timeout=30)
    if waf_name:
        return _build_firewall_result(waf_name, evidence)

    # Step 3: No CDN or WAF detected
    return {
        "detected": False,
        "firewall_name": None,
        "cdn_detected": False,
        "waf_detected": False,
        "cdn_name": None,
        "waf_name": None,
        "evidence": evidence or "No CDN or WAF indicators found",
    }