# ── Email Notifier Module ──────────────────────────────────
import smtplib
import json
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from typing import Dict, Optional

CONFIG_FILE = "email_config.json"

def load_config() -> Dict:
    try:
        with open(CONFIG_FILE, "r") as f:
            return json.load(f)
    except:
        return {"sender_email": "", "app_password": "", "recipient_emails": ""}

def save_config(config: Dict):
    with open(CONFIG_FILE, "w") as f:
        json.dump(config, f, indent=2)


async def send_email_notification(url: str, scan_result: Dict, pdf_path: Optional[str] = None):
    """Send email notification with scan results"""
    try:
        config = load_config()
        sender = config.get("sender_email", "").strip()
        password = config.get("app_password", "").strip()
        recipients_raw = config.get("recipient_emails", "").strip()
        
        if not sender or not password or not recipients_raw:
            print("[EMAIL] Config missing, skipping")
            return
        
        recipients = [r.strip() for r in recipients_raw.split(",") if r.strip()]
        if not recipients:
            print("[EMAIL] No recipients")
            return
        
        scan_id = scan_result.get("scan_id", "N/A")
        timestamp = scan_result.get("timestamp", datetime.now().isoformat())
        
        subject = f"[RECON TOOL] Scan Complete: {url}"
        
        body = f"""
╔══════════════════════════════════════╗
║     SCAN COMPLETE REPORT            ║
╚══════════════════════════════════════╝

📍 Target URL: {url}
🆔 Scan ID: {scan_id}
🕐 Time: {timestamp}

📊 SUMMARY:
─────────────────────────────────────
🔐 SSL: {scan_result.get('ssl', {}).get('issued_to', 'N/A') if scan_result.get('ssl') else 'N/A'}
🛡️ Security Score: {scan_result.get('security_headers', {}).get('score', 0) if scan_result.get('security_headers') else 0}/100
🔌 Open Ports: {scan_result.get('ports', {}).get('total_open', 0) if scan_result.get('ports') else 0}
🌐 Subdomains: {scan_result.get('subdomains', {}).get('total_found', 0) if scan_result.get('subdomains') else 0}
📄 Endpoints: {scan_result.get('crawl', {}).get('total_found', 0) if scan_result.get('crawl') else 0}

📎 PDF Report: {'✅ Generated' if pdf_path else '❌ Not available'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
View full report in dashboard:
http://localhost:8000/?scan_id={scan_id}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Generated by Recon Tool v1.0
"""
        
        msg = MIMEMultipart()
        msg['From'] = sender
        msg['To'] = ", ".join(recipients)
        msg['Subject'] = subject
        msg.attach(MIMEText(body, "plain"))
        
        if pdf_path and os.path.exists(pdf_path):
            with open(pdf_path, 'rb') as f:
                part = MIMEBase('application', 'octet-stream')
                part.set_payload(f.read())
                encoders.encode_base64(part)
                part.add_header('Content-Disposition', f'attachment; filename={Path(pdf_path).name}')
                msg.attach(part)
        
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(sender, password)
        server.send_message(msg)
        server.quit()
        
        print(f"[EMAIL] ✅ Sent to {len(recipients)} recipient(s)")
        return True
        
    except Exception as e:
        print(f"[EMAIL] ❌ Failed: {e}")
        return False